name: Create and Push Frontend Docker

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          
    - uses: actions/checkout@v4
    -
      name: Build and push api
      uses: docker/build-push-action@v6
      with:
        context: ./src/api
        file: ./src/api/Dockerfile
        build-args: DATABASE_URL=${{ secrets.DATABASE_URL }}
        push: true
        tags: stumpisuter/augur-hakesch-api:latest
    -
      name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
        context: ./src/frontend
        file: ./src/frontend/Dockerfile
        build-args: DATABASE_URL=${{ secrets.DATABASE_URL }}
        push: true
        tags: stumpisuter/augur-hakesch-frontend:latest
